name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ----------------------
      # Checkout
      # ----------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ----------------------
      # Python Backend Setup
      # ----------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          else
            echo "No backend requirements.txt found, skipping..."
          fi

      # ----------------------
      # Node/React Frontend Setup
      # ----------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm install
          else
            echo "No frontend package.json found, skipping..."
          fi

      - name: Build React frontend
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            CI=false npm run build --if-present
          else
            echo "No React frontend found, skipping build..."
          fi

      # ----------------------
      # (Optional) Run backend tests
      # ----------------------
      - name: Run Python tests
        run: |
          if [ -d backend/tests ]; then
            pytest backend/tests
          else
            echo "No backend tests found, skipping..."
          fi
